name: demo_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio:
  provider: ^6.1.1
  adaptive_theme: ^3.4.1
  fdottedline_nullsafety: ^2.0.1
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  custom_clippers: ^1.0.0
  loading_animation_widget: ^1.2.0+4
  #  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  coupon_uikit: ^0.2.0
  cached_network_image: ^3.1.0
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  gap: ^3.0.1
  dio_http_cache: ^0.3.0
  connection_notifier: ^2.0.1
  photo_view: ^0.14.0
  insta_image_viewer: ^1.0.2
  awesome_notifications: ^0.8.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_core_platform_interface: ^5.0.0
  #  flutter_map: ^6.1.0
  latlong2: ^0.8.1
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^1.0.0
  flutter_osm_plugin:
  cloud_firestore: ^4.14.0
  firebase_crashlytics: ^3.4.9
  freezed: ^0.14.2
  build_runner: ^2.1.8
  json_serializable:
  json_annotation:
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2
  signature: ^5.4.1
  path_provider: ^2.1.2
  syncfusion_flutter_pdfviewer:
  syncfusion_flutter_pdf:
  syncfusion_flutter_signaturepad:
  open_file: ^3.3.2
  image: ^4.1.7
  http:
  draggable_widget: ^2.0.0
  permission_handler:
  image_gallery_saver: ^2.0.3
  pdf: ^3.10.7
  flutter_signature_pad: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/certificate.pfx
    - assets/pdf/flutter.pdf


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
